models:
  - provider: vllm
    model: Qwen/Qwen2-VL-2B-Instruct
    api_key:  ${HF_TOKEN}# AS HF key
  - provider: vllm
    model: HuggingFaceTB/SmolLM2-135M-Instruct
    api_key:  ${HF_TOKEN}# AS HF key
  - provider: vllm
    model: Qwen/Qwen2.5-0.5B
    api_key:  ${HF_TOKEN}# AS HF key
  - provider: vllm
    model: ICTNLP/LLaMA-Omni2-0.5B
    api_key: ${HF_TOKEN}
  - provider: vllm
    model: turboderp/Qwama-0.5B-Instruct
    api_key: ${HF_TOKEN}
  - provider: vllm
    model: tencent/Hunyuan-0.5B-Instruct
    api_key: ${HF_TOKEN}
temperature: 0.0
max_tokens: 10

system_message: # set a custom system message

# (for custom OpenAI-compatible API)
provider_kwargs:
  base_url: http://localhost:8000/v1 # example for vllm default

rate_limiting:
  enabled: false
  requests_per_minute: 10

limit: # limit to n examples
fast: true # use CoT or not

data:
  data_file: ./italic.jsonl
  few_shot_file: ./5_shots.jsonl # Set as null to run zero-shot evaluation
  output_dir: results

num_threads: 10

auto_resume: true # resume from last checkpoint

checkpointing:
  enabled: true
  checkpoint_interval: 50
